### ISSUE TITLE
Great Job Everyone!! 🙌😍

### ISSUE THREAD

**Issue by reubengt** [fac18/dynamyk-site#10]
## "We began by closing our laptops" - A great start to a great project 👌
![bruno-mars-10-gif](https://media.giphy.com/media/ar4x1w44umngk/giphy.gif)
- I love the consistent, clean design, super legible and easy to read!
- making wireframes before coding is a great idea! keep doing this on future projects! 🥇 
- solid breakdown of git flow on the README, I can see that its starting to sink in. The main purpose of this week's project is to work as a team with git, so well done!
- really good structure on your HTML, semantically fantastic, fantastically semantic 🤸‍♀ 
- PARALLAX! such a cool thing to look at, bonus points for this 🍾 🎉 
- CSS is structured according to page flow, which is always great for readability.
- I quite enjoyed DJing on your turntables/profile pictures. funky little animation there 😆 

![pizza cat dj](https://media.giphy.com/media/aCKMaeduKfFXG/giphy.gif)

## REALLY SOLID FIRST PROJECT, EXCITED TO SEE MORE FROM YOU LOT!

**Comment by tloth** [comment]
wow @reubengt any compliment I give will sound fake and/or unimportant next to this bouquet of amaze

**Comment by tloth** [comment]
WOW IT'S A FLIPPIN AMAZING FIRST PROJECT :sparkles:
![woww](https://media3.giphy.com/media/fAykJdJ6SYSYw/source.gif)

**Comment by bobbysebolao** [comment]
![great job delicious](https://media.giphy.com/media/dyjKyk1u5RoPm6G54u/giphy.gif)

**Comment by plasticneuron** [comment]
Thank you all this is really nice to read! :)

**Comment by redahaq** [comment]
Thank you so much @reubengt @tloth! 

It was such a delight to read through all your comments. You've given us a great understanding of what to look out for when reviewing code andhow to write issues in an encouraging, helpful and fun way. 

![](https://media.giphy.com/media/xULW8v7LtZrgcaGvC0/giphy.gif)
