### ISSUE TITLE
Site doesn't quite fill the screen

### ISSUE THREAD

**Issue by reubengt** [fac18/dynamyk-site#12]
So the reason i'm bringing this up is because the entire site has a white border around it, it's not quite touching the sides 😅
(hint: it's something the browser is doing, not your code)

**Fire up devtools(right click->inspect, or command+option+i on mac, control+shift+i on linux) to find out why!**

Different browsers have different things they apply to your css by default, and a css reset aims to switch off these defaults so that you're starting from the same point in all browsers.
There's loads of different ways to do a css reset, and I would recommend doing some research about this as they can vary a lot.
here's two popular ones:
https://necolas.github.io/normalize.css/
https://meyerweb.com/eric/tools/css/reset/

That being said, sometimes it's not necessary to remove all default browser styling, and you might want to start by just removing what's being affected.

**Comment by redahaq** [comment]
Thanks @reubengt - yes, we had a few issues with 'user-agent-stylesheet'. We used inspect to resolve some of them like margin-block-start and margin-block-end values adding unwanted space.

This info about CSS reset is *soooooo* helpful! Really appreciate it.
