### ISSUE TITLE
Using an image for text doesn't scale well 😬

### ISSUE THREAD

**Issue by reubengt** [fac18/dynamyk-site#13]
The main heading is an image(png), which means it doesnt scale well on larger screens(causes pixelation) 
A couple possible solutions:
- SVG: a really cool web focussed alternative to image files for things like icons, scalability is in the name. looks the same no matter how large it gets. ask bobby for more guidance, he is an svg wizard.
- Text. since the h1 is the same font as your other headings, making it text, with the font-size changing according to the screen size.
This would provide the same responsiveness, and look sharper on large screens (as fonts are vectors that are designed to scale)

It's a minor change, but pixelation on a website will throw off end users, especially since today's displays are so sharp and detailed 

**I've attached two files, one being the current image based implementation, the other using text instead of an image, might have to zoom in to see the difference**

### heading is img
<img width="1440" alt="Screenshot 2019-10-31 at 20 58 07" src="https://user-images.githubusercontent.com/42008435/67993796-5e2fbb80-fc3a-11e9-9d9b-e1fd54a413c5.png">

### heading is text inside an h1 tag (find the magic ingredient, a responsive font size)
<img width="1440" alt="Screenshot 2019-10-31 at 20 58 32" src="https://user-images.githubusercontent.com/42008435/67993807-67b92380-fc3a-11e9-9df4-571c856435cd.png">

**Comment by redahaq** [comment]
Cheers! Great point. We actually started with text but it was massively overflowing on mobile; we  thought a logo might scale in a more smooth, responsive way rather than in a media-query snap manner... turns out, not so! (at least when using png).

Luckily we kept this code and commented it out so resolving this issue should be fairly simple.

Look forward to diving into SVGs in due course.

**Comment by redahaq** [comment]
Resolved for desktop and mobile but given more time we would use an SVG ideally, or add more media queries avoid overflow on middle-sized devices - tablets etc
