### ISSUE TITLE
commit messages

### ISSUE THREAD

**Issue by tloth** [fac18/dynamyk-site#14]
Nice first commits, yall!!

Commit messages are helpful when you want to search through your git log, see the history of your code, find where it all went terribly wrong.

Commit message standards and best practices have been widely debated, as, just like almost everything else in the world of tech, it all comes down to personal preference.

Start your message with a capital letter? Lowercase everything? Use the present simple? Past simple?? Future??? (Ok maybe not the future lol.) Use the base form of verbs? (yes plz this is my personal preference) Endless possibilities :ocean:

There is only one _good_ practice, and that is _*CONSISTENCY*_. In the first few weeks of your coding, it doesn't really matter that much, so please go and experiment!! What feels right, what feels like _you_? (lol) And once you've found it, stick to it. Later on, in bigger projects, you might have a process guide in which the preferred way of writing a commit message is set, so at least then you don't have to think too much about it, and even in big companies, and even CTOs write ugly-ass commit messages sometimes, so don't worry about it too much right now. Just have it linger in the back of your mind.

Semantically, a commit should be simple and to the point, no dilly dally. A short line to summarise what the code does now after you've changed it, and if you want to add more, you can hit Enter, and elaborate there. A commit message will go until you close that quote mark. At this point, you really don't need to elaborate, try to be simply clever like skoda.

Here are two great resources explaining the art of commit messages - _use them well_.
- an article https://chris.beams.io/posts/git-commit/
- a talk by Joel Chippindale https://www.youtube.com/watch?v=qpdYRPL3SVE and his slides https://www.slideshare.net/joelchippindale/telling-stories-through-your-commits

```git commit -m 'add superlong issue about commit messages'```

**Comment by reubengt** [comment]
A commit sonnet
- anna t, 2019

**Comment by plasticneuron** [comment]
Hey Anna thanks for this discussion on git commits, I've definitely wondered what's standard. Glad to hear there's flexibility there! Will read the articles :)
