### ISSUE TITLE
html fiasco

### ISSUE THREAD

**Issue by tloth** [fac18/dynamyk-site#15]
https://github.com/fac18/dynamyk-site/blob/9dd746b07d78e4fcd9fa95e5328f215b86070692/index.html#L40

There may not be a gender binary, but there sure is a html binary - meaning if you start a tag, please close that same tag! The closing tag is either correct or not :)) The browser will fix this for you, so not a major problem, but there was a wild second when I thought I was in another dimension.

p.s. the "fiasco" is obviously a disgusting exaggeration

**Comment by tloth** [comment]
BTW!! Really nice use of the heading hierarchy! :clap:

**Comment by redahaq** [comment]
@tloth We've renamed our team as 'Fiasco' for week 2, in tribute. ;)

**Comment by tloth** [comment]
omg :DD
