### ISSUE TITLE
🍔HAMBURGER menu! brilliant!

### ISSUE THREAD

**Issue by reubengt** [fac18/dynamyk-site#19]
if you came up with it, congrats, it's a really interesting implementation :confetti_ball: :sparkles: 

A label that triggers a checkbox, visual changes based on the checked state of the checkbox.. no JS! 

the :before and :after pseudo-elements are quite interesting, I remember learning about them being like woah they're ninja elements :astonished:

i would try and rewrite the the css to not use floats though, flexbox is your friend :D

**Comment by tloth** [comment]
yes, also well done on using child selectors

**Comment by bobbysebolao** [comment]
![yes](https://media.giphy.com/media/3o6ZteX8cqJRH4TwQ0/giphy.gif)
