### ISSUE TITLE
so much awesome about the UI

### ISSUE THREAD

**Issue by tloth** [fac18/dynamyk-site#21]
Ah. So good.

My personal favourite is the linear gradient going from a colour to an image - what a concept!!!

All the "jazzy CSS tricks [...] just for the hell of it" - I am HERE for this. I spent the first 20 minutes of this code review just spinning your faces around.  Little opaque to clear and back. No regrets.

The simple colours are great - the simpler, the better. Good contrast, awesome for accessibility.

**Comment by reubengt** [comment]
YES AGREE 100%!!
![](http://giphygifs.s3.amazonaws.com/media/sI9zGC4bh9eCI/giphy.gif)

**Comment by Oliversw** [comment]
AGREED! I love the portraits spinning on hover! One of my favourite things that I try to sneak into every project soooo 👍 👍 👍

**Comment by Ayub3** [comment]
That was the best part of the site :sunglasses: :sunglasses:
