### ISSUE TITLE
some insight into forms

### ISSUE THREAD

**Issue by reubengt** [fac18/dynamyk-site#22]
I noticed that your form has an action property... this is telling the form what to do with the data you enter(where to send it). If you look into the address bar after you click submit, you'll see the names and values of your inputs in a format like this

https://fac18.github.io/form-data?client-name=value1&client-email=email%40email.org&client-message=FAC18+is+cool

this is submitting this form and expecting some form of answer from your website, your website/github pages says "there's nothing here" because it doesnt know what to do with this data.

in week 4 you'll learn how to send stuff back, or do things with form input! exciting stuff.

But if you're feeling adventurous, since this was mentioned as a stretch goal in your readme, here's a link to [hook up a form with google sheets](https://github.com/jamiewilson/form-to-google-sheets)

In this case, you're submitting the form to google sheets, and adding some code there to tell google sheets what to do with the form data.

You're not expected to understand any of this at this point, don't worry.
It's super cool that you thought of making your form store submitted data, so I thought I'd share some insight 😄

**Comment by plasticneuron** [comment]
Very handy, thanks Reuben! Might try and implement this for the heck of it :)
