### ISSUE TITLE
Commits and Contributions

### ISSUE THREAD

**Issue by gminova** [fac18/dynamyk-site#23]
It seems like there is not a balanced share of the workload. Something to keep an eye for in the future. Remember to commit regularly, switch machines and swap pairs when working together.

![Screenshot from 2019-11-01 10-49-52](https://user-images.githubusercontent.com/42014388/68020117-636e2400-fc95-11e9-8d35-71d8680dfebb.png)
![Screenshot from 2019-11-01 10-49-59](https://user-images.githubusercontent.com/42014388/68020118-636e2400-fc95-11e9-8131-2d0deb05f44b.png)

**Comment by plasticneuron** [comment]
Thanks Gigi this is good to keep an eye on!
