### ISSUE TITLE
Some CSS selectors need better descriptions eg ".fab"

### ISSUE THREAD

**Issue by nikkesan** [fac18/dynamyk-site#32]
Which icon does ".fab" refer to?

**Comment by reubengt** [comment]
yesss I was hoping someone else brought this up 👏👏

**Comment by bethanyios** [comment]
This refers to our font awesome icons - their copy-paste code includes this class. Then we specified for codewars as it isn't available on font-awesome. 

Noted though - we should add an inline comment to avoid confusion!! 
☺️

**Comment by plasticneuron** [comment]
Aye I don't think we should style via the fab class because we might override some essential aspect of styling set by the font-awesome. It's also not BEM consistent. Thanks for picking this up.

**Comment by redahaq** [comment]
Such an interesting point, @plasticneuron. We could declare own class after the fab class. 

I used .fab and .fas on my application website as it meant that any new fontawesome icons I added would be automatically styled.

I see pros and cons to both approaches! Good point about BEM!
